// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCumRw3sFvsXR06KgJ2KPM6TQI6y-SLC4c',
    appId: '1:1076375118385:web:ecba34afc3d0508f212b10',
    messagingSenderId: '1076375118385',
    projectId: 'pruebahackaton-bfb64',
    authDomain: 'pruebahackaton-bfb64.firebaseapp.com',
    storageBucket: 'pruebahackaton-bfb64.firebasestorage.app',
    measurementId: 'G-EPM34J42T3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDgQURFFMjz7oP7axbgf_EuO9PYAIQHw4U',
    appId: '1:1076375118385:android:57fb4b8a958cc1a2212b10',
    messagingSenderId: '1076375118385',
    projectId: 'pruebahackaton-bfb64',
    storageBucket: 'pruebahackaton-bfb64.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDl65qiisn3jgbTP5a4ubkFXDvC9can2nw',
    appId: '1:1076375118385:ios:5a6ec5c41770fca2212b10',
    messagingSenderId: '1076375118385',
    projectId: 'pruebahackaton-bfb64',
    storageBucket: 'pruebahackaton-bfb64.firebasestorage.app',
    iosBundleId: 'com.example.prueba2app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDl65qiisn3jgbTP5a4ubkFXDvC9can2nw',
    appId: '1:1076375118385:ios:5a6ec5c41770fca2212b10',
    messagingSenderId: '1076375118385',
    projectId: 'pruebahackaton-bfb64',
    storageBucket: 'pruebahackaton-bfb64.firebasestorage.app',
    iosBundleId: 'com.example.prueba2app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCumRw3sFvsXR06KgJ2KPM6TQI6y-SLC4c',
    appId: '1:1076375118385:web:3e5d117feb67e074212b10',
    messagingSenderId: '1076375118385',
    projectId: 'pruebahackaton-bfb64',
    authDomain: 'pruebahackaton-bfb64.firebaseapp.com',
    storageBucket: 'pruebahackaton-bfb64.firebasestorage.app',
    measurementId: 'G-RXZXW0JJ9V',
  );
}
